### ISSUE TITLE
Export Stream Tool  (ConfigureStream)

### ISSUE THREAD

**Issue by palmerss** [rohatgia/CMSC314_SeniorProject#15]
This Tool should allow you to Export the selected Stream to an arff file (this can be done using the MOA API)

upon clicking this button you will enter a name for the file and then afterwards the file is exported

**Comment by rohatgia** [comment]
Latest commit adds functionality for this issue:
 - Retrieves stream from local ArrayList
 - Calls editStream to retrieve details about desired stream to export
 - Make calls to WriteARFFFileStream method in moa.tasks
 - Edit public variables, which are used (and called) in the doMainTask function
 - Non-functional pending Tuesday review session

**Comment by palmerss** [comment]
DONE 11/6/17
