### ISSUE TITLE
Add Stream Button (Configure Stream Menu)

### ISSUE THREAD

**Issue by palmerss** [rohatgia/CMSC314_SeniorProject#5]
As a user, when I select the add stream Menu I want to type in a file name and that file be loaded into the environment and appear in the Configure Stream Menu

**Comment by palmerss** [comment]
For now Streams should just be an ArffFileStream Object that is part of the MOA Package.

**Comment by rohatgia** [comment]
Latest commit adds functionality for this issue:
 - Request stream name
 - Makes call to ArffFileStream
 - Stores in local ArrayList in ConfigureStream (merge this into the arraylist in the menu?)

**Comment by palmerss** [comment]
DONE 11/6/17
